version: '3.8'

services:
  todo-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/todo-app
      - JWT_SECRET=your-production-jwt-secret-change-this
      - JWT_EXPIRE=7d
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=todo-app
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
